{ lib, uint, ... } : {
  "xfce4-power-manager/battery-button-action" = lib.mkDefault (uint 0); # nothing
  "xfce4-power-manager/blank-on-ac" = lib.mkDefault 0; # never
  "xfce4-power-manager/blank-on-battery" = lib.mkDefault 0; # never
  "xfce4-power-manager/brightness-exponential" = lib.mkDefault false;
  "xfce4-power-manager/brightness-level-on-ac" = lib.mkDefault (uint 100);
  "xfce4-power-manager/brightness-level-on-battery" = lib.mkDefault (uint 100);
  "xfce4-power-manager/brightness-on-ac" = lib.mkDefault (uint 9); # never
  "xfce4-power-manager/brightness-on-battery" = lib.mkDefault (uint 9); # never
  "xfce4-power-manager/brightness-step-count" = lib.mkDefault (uint 10);
  "xfce4-power-manager/critical-power-action" = lib.mkDefault (uint 2); # hybrid-sleep
  "xfce4-power-manager/critical-power-level" = lib.mkDefault (uint 10);
  "xfce4-power-manager/dpms-enabled" = lib.mkDefault false; # lock screen when display turns off?
  "xfce4-power-manager/dpms-on-ac-off" = lib.mkDefault (uint 0); # never
  "xfce4-power-manager/dpms-on-ac-sleep" = lib.mkDefault (uint 0); # never
  "xfce4-power-manager/dpms-on-battery-off" = lib.mkDefault (uint 10);
  "xfce4-power-manager/dpms-on-battery-sleep" = lib.mkDefault (uint 10);
  "xfce4-power-manager/general-notification" = lib.mkDefault false;
  "xfce4-power-manager/handle-brightness-keys" = lib.mkDefault true;
  "xfce4-power-manager/hibernate-button-action" = lib.mkDefault (uint 2); # hybrid-sleep
  "xfce4-power-manager/inactivity-on-ac" = lib.mkDefault (uint 14); # never
  "xfce4-power-manager/inactivity-on-battery" = lib.mkDefault (uint 20);
  "xfce4-power-manager/inactivity-sleep-mode-on-ac" = lib.mkDefault (uint 1); # suspend
  "xfce4-power-manager/inactivity-sleep-mode-on-battery" = lib.mkDefault (uint 1); # suspend
  "xfce4-power-manager/lid-action-on-battery" = lib.mkDefault (uint 1); # suspend
  "xfce4-power-manager/lid-action-on-ac" = lib.mkDefault (uint 0); # switch off display
  "xfce4-power-manager/lock-screen-suspend-hibernate" = lib.mkDefault false;
  "xfce4-power-manager/logind-handle-lid-switch" = lib.mkDefault false;
  "xfce4-power-manager/power-button-action" = lib.mkDefault (uint 2); # hybrid-sleep
  "xfce4-power-manager/show-panel-label" = lib.mkDefault 1; # percentage
  "xfce4-power-manager/show-presentation-indicator" = lib.mkDefault true;
  "xfce4-power-manager/show-tray-icon" = lib.mkDefault false;
  "xfce4-power-manager/sleep-button-action" = lib.mkDefault (uint 1); # suspend
}
